/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Product guides — each product gets its own isolated sidebar
  screenSidebar:     [{ type: 'autogenerated', dirName: 'hackerrank-screen' }],
  interviewsSidebar: [{ type: 'autogenerated', dirName: 'interviews' }],
  engageSidebar:     [{ type: 'autogenerated', dirName: 'engage' }],
  skillupSidebar:    [{ type: 'autogenerated', dirName: 'skillup' }],
  chakraSidebar:     [{ type: 'autogenerated', dirName: 'chakra' }],

  // Platform guides — Library and Settings as two distinct top-level sections
  platformSidebar: [
    { type: 'autogenerated', dirName: 'library' },
    { type: 'autogenerated', dirName: 'account-settings' },
  ],

  // Integrations — standalone
  integrationsSidebar: [{ type: 'autogenerated', dirName: 'integrations-1' }],

  // Release notes — isolated
  releaseNotesSidebar: [
    { type: 'autogenerated', dirName: 'release-notes' },
  ],

  // Additional resources — each category as its own top-level section (no umbrella)
  additionalSidebar: [
    { type: 'autogenerated', dirName: 'general-help/academy' },
    { type: 'autogenerated', dirName: 'general-help/hackerrank-ai' },
    { type: 'autogenerated', dirName: 'general-help/hackerrank_ai_data_services' },
    { type: 'autogenerated', dirName: 'general-help/campus' },
    { type: 'autogenerated', dirName: 'general-help/deprecations_and_experience_changes' },
    { type: 'autogenerated', dirName: 'general-help/evaluation-guides' },
    { type: 'autogenerated', dirName: 'general-help/additional_resources-1' },
    { type: 'autogenerated', dirName: 'general-help/important-notifications' },
    { type: 'autogenerated', dirName: 'general-help/office-hours' },
    { type: 'autogenerated', dirName: 'uncategorized' },
  ],
};

module.exports = sidebars;
