/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Product guides — each product gets its own isolated sidebar
  screenSidebar:     [{ type: 'autogenerated', dirName: 'hackerrank-screen' }],
  interviewsSidebar: [{ type: 'autogenerated', dirName: 'interviews' }],
  engageSidebar:     [{ type: 'autogenerated', dirName: 'engage' }],
  skillupSidebar:    [{ type: 'autogenerated', dirName: 'skillup' }],
  chakraSidebar:     [{ type: 'autogenerated', dirName: 'chakra' }],

  // Platform guides — Library + Settings together
  platformSidebar: [
    { type: 'autogenerated', dirName: 'library' },
    { type: 'autogenerated', dirName: 'account-settings' },
  ],

  // Integrations — standalone
  integrationsSidebar: [{ type: 'autogenerated', dirName: 'integrations-1' }],

  // Release notes / General help
  generalSidebar: [
    { type: 'autogenerated', dirName: 'general-help' },
    { type: 'autogenerated', dirName: 'uncategorized' },
  ],
};

module.exports = sidebars;
